/*
 * Mesa Register Helper Macros
 * Auto-generated helper macros for constructing register values
 */

#ifndef MESA_HELPERS_H
#define MESA_HELPERS_H

#include <stdint.h>

/* Helper macros to construct bitfield values */
#define PC_OPERATION_ENABLE_RESERVED_0(x) (((uint32_t)(x) << PC_OPERATION_ENABLE_RESERVED_0__SHIFT) & PC_OPERATION_ENABLE_RESERVED_0__MASK)
#define PC_OPERATION_ENABLE_OP_EN(x) (((uint32_t)(x) << PC_OPERATION_ENABLE_OP_EN__SHIFT) & PC_OPERATION_ENABLE_OP_EN__MASK)

#define CNA_CBUF_CON0_WEIGHT_BANK(x) (((uint32_t)(x) << CNA_CBUF_CON0_WEIGHT_BANK__SHIFT) & CNA_CBUF_CON0_WEIGHT_BANK__MASK)
#define CNA_CBUF_CON0_DATA_BANK(x) (((uint32_t)(x) << CNA_CBUF_CON0_DATA_BANK__SHIFT) & CNA_CBUF_CON0_DATA_BANK__MASK)

#define CNA_CBUF_CON1_DATA_ENTRIES(x) (((uint32_t)(x) << CNA_CBUF_CON1_DATA_ENTRIES__SHIFT) & CNA_CBUF_CON1_DATA_ENTRIES__MASK)

#define CNA_CONV_CON1_CONV_MODE(x) (((uint32_t)(x) << CNA_CONV_CON1_CONV_MODE__SHIFT) & CNA_CONV_CON1_CONV_MODE__MASK)
#define CNA_CONV_CON1_IN_PRECISION(x) (((uint32_t)(x) << CNA_CONV_CON1_IN_PRECISION__SHIFT) & CNA_CONV_CON1_IN_PRECISION__MASK)
#define CNA_CONV_CON1_PROC_PRECISION(x) (((uint32_t)(x) << CNA_CONV_CON1_PROC_PRECISION__SHIFT) & CNA_CONV_CON1_PROC_PRECISION__MASK)

#define CNA_CONV_CON2_FEATURE_GRAINS(x) (((uint32_t)(x) << CNA_CONV_CON2_FEATURE_GRAINS__SHIFT) & CNA_CONV_CON2_FEATURE_GRAINS__MASK)

#define CNA_CONV_CON3_CONV_X_STRIDE(x) (((uint32_t)(x) << CNA_CONV_CON3_CONV_X_STRIDE__SHIFT) & CNA_CONV_CON3_CONV_X_STRIDE__MASK)
#define CNA_CONV_CON3_CONV_Y_STRIDE(x) (((uint32_t)(x) << CNA_CONV_CON3_CONV_Y_STRIDE__SHIFT) & CNA_CONV_CON3_CONV_Y_STRIDE__MASK)

#define CNA_DATA_SIZE0_DATAIN_WIDTH(x) (((uint32_t)(x) << CNA_DATA_SIZE0_DATAIN_WIDTH__SHIFT) & CNA_DATA_SIZE0_DATAIN_WIDTH__MASK)
#define CNA_DATA_SIZE0_DATAIN_HEIGHT(x) (((uint32_t)(x) << CNA_DATA_SIZE0_DATAIN_HEIGHT__SHIFT) & CNA_DATA_SIZE0_DATAIN_HEIGHT__MASK)

#define CNA_DATA_SIZE1_DATAIN_CHANNEL(x) (((uint32_t)(x) << CNA_DATA_SIZE1_DATAIN_CHANNEL__SHIFT) & CNA_DATA_SIZE1_DATAIN_CHANNEL__MASK)
#define CNA_DATA_SIZE1_DATAIN_CHANNEL_REAL(x) (((uint32_t)(x) << CNA_DATA_SIZE1_DATAIN_CHANNEL_REAL__SHIFT) & CNA_DATA_SIZE1_DATAIN_CHANNEL_REAL__MASK)

#define CNA_DATA_SIZE2_DATAOUT_WIDTH(x) (((uint32_t)(x) << CNA_DATA_SIZE2_DATAOUT_WIDTH__SHIFT) & CNA_DATA_SIZE2_DATAOUT_WIDTH__MASK)

#define CNA_DATA_SIZE3_DATAOUT_ATOMICS(x) (((uint32_t)(x) << CNA_DATA_SIZE3_DATAOUT_ATOMICS__SHIFT) & CNA_DATA_SIZE3_DATAOUT_ATOMICS__MASK)

#define CNA_WEIGHT_SIZE2_WEIGHT_WIDTH(x) (((uint32_t)(x) << CNA_WEIGHT_SIZE2_WEIGHT_WIDTH__SHIFT) & CNA_WEIGHT_SIZE2_WEIGHT_WIDTH__MASK)
#define CNA_WEIGHT_SIZE2_WEIGHT_HEIGHT(x) (((uint32_t)(x) << CNA_WEIGHT_SIZE2_WEIGHT_HEIGHT__SHIFT) & CNA_WEIGHT_SIZE2_WEIGHT_HEIGHT__MASK)
#define CNA_WEIGHT_SIZE2_WEIGHT_KERNELS(x) (((uint32_t)(x) << CNA_WEIGHT_SIZE2_WEIGHT_KERNELS__SHIFT) & CNA_WEIGHT_SIZE2_WEIGHT_KERNELS__MASK)

#define CNA_CVT_CON0_DATA_SIGN(x) (((uint32_t)(x) << CNA_CVT_CON0_DATA_SIGN__SHIFT) & CNA_CVT_CON0_DATA_SIGN__MASK)
#define CNA_CVT_CON0_CVT_TYPE(x) (((uint32_t)(x) << CNA_CVT_CON0_CVT_TYPE__SHIFT) & CNA_CVT_CON0_CVT_TYPE__MASK)
#define CNA_CVT_CON0_CVT_BYPASS(x) (((uint32_t)(x) << CNA_CVT_CON0_CVT_BYPASS__SHIFT) & CNA_CVT_CON0_CVT_BYPASS__MASK)

#define CNA_CVT_CON1_CVT_SCALE0(x) (((uint32_t)(x) << CNA_CVT_CON1_CVT_SCALE0__SHIFT) & CNA_CVT_CON1_CVT_SCALE0__MASK)
#define CNA_CVT_CON2_CVT_SCALE1(x) (((uint32_t)(x) << CNA_CVT_CON2_CVT_SCALE1__SHIFT) & CNA_CVT_CON2_CVT_SCALE1__MASK)
#define CNA_CVT_CON3_CVT_SCALE2(x) (((uint32_t)(x) << CNA_CVT_CON3_CVT_SCALE2__SHIFT) & CNA_CVT_CON3_CVT_SCALE2__MASK)
#define CNA_CVT_CON4_CVT_SCALE3(x) (((uint32_t)(x) << CNA_CVT_CON4_CVT_SCALE3__SHIFT) & CNA_CVT_CON4_CVT_SCALE3__MASK)

#define CORE_MISC_CFG_QD_EN(x) (((uint32_t)(x) << CORE_MISC_CFG_QD_EN__SHIFT) & CORE_MISC_CFG_QD_EN__MASK)

#define CORE_DATAOUT_SIZE_0_DATAOUT_WIDTH(x) (((uint32_t)(x) << CORE_DATAOUT_SIZE_0_DATAOUT_WIDTH__SHIFT) & CORE_DATAOUT_SIZE_0_DATAOUT_WIDTH__MASK)
#define CORE_DATAOUT_SIZE_0_DATAOUT_HEIGHT(x) (((uint32_t)(x) << CORE_DATAOUT_SIZE_0_DATAOUT_HEIGHT__SHIFT) & CORE_DATAOUT_SIZE_0_DATAOUT_HEIGHT__MASK)

#define CORE_DATAOUT_SIZE_1_DATAOUT_CHANNEL(x) (((uint32_t)(x) << CORE_DATAOUT_SIZE_1_DATAOUT_CHANNEL__SHIFT) & CORE_DATAOUT_SIZE_1_DATAOUT_CHANNEL__MASK)

#define DPU_S_POINTER_POINTER_PP_MODE(x) (((uint32_t)(x) << DPU_S_POINTER_POINTER_PP_MODE__SHIFT) & DPU_S_POINTER_POINTER_PP_MODE__MASK)
#define DPU_S_POINTER_EXECUTER_PP_EN(x) (((uint32_t)(x) << DPU_S_POINTER_EXECUTER_PP_EN__SHIFT) & DPU_S_POINTER_EXECUTER_PP_EN__MASK)
#define DPU_S_POINTER_POINTER_PP_EN(x) (((uint32_t)(x) << DPU_S_POINTER_POINTER_PP_EN__SHIFT) & DPU_S_POINTER_POINTER_PP_EN__MASK)

#define DPU_RDMA_RDMA_S_POINTER_POINTER_PP_MODE(x) (((uint32_t)(x) << DPU_RDMA_RDMA_S_POINTER_POINTER_PP_MODE__SHIFT) & DPU_RDMA_RDMA_S_POINTER_POINTER_PP_MODE__MASK)
#define DPU_RDMA_RDMA_S_POINTER_EXECUTER_PP_EN(x) (((uint32_t)(x) << DPU_RDMA_RDMA_S_POINTER_EXECUTER_PP_EN__SHIFT) & DPU_RDMA_RDMA_S_POINTER_EXECUTER_PP_EN__MASK)
#define DPU_RDMA_RDMA_S_POINTER_POINTER_PP_EN(x) (((uint32_t)(x) << DPU_RDMA_RDMA_S_POINTER_POINTER_PP_EN__SHIFT) & DPU_RDMA_RDMA_S_POINTER_POINTER_PP_EN__MASK)

#define DPU_FEATURE_MODE_CFG_BURST_LEN(x) (((uint32_t)(x) << DPU_FEATURE_MODE_CFG_BURST_LEN__SHIFT) & DPU_FEATURE_MODE_CFG_BURST_LEN__MASK)
#define DPU_FEATURE_MODE_CFG_OUTPUT_MODE(x) (((uint32_t)(x) << DPU_FEATURE_MODE_CFG_OUTPUT_MODE__SHIFT) & DPU_FEATURE_MODE_CFG_OUTPUT_MODE__MASK)

#define DPU_DATA_CUBE_CHANNEL_ORIG_CHANNEL(x) (((uint32_t)(x) << DPU_DATA_CUBE_CHANNEL_ORIG_CHANNEL__SHIFT) & DPU_DATA_CUBE_CHANNEL_ORIG_CHANNEL__MASK)
#define DPU_DATA_CUBE_CHANNEL_CHANNEL(x) (((uint32_t)(x) << DPU_DATA_CUBE_CHANNEL_CHANNEL__SHIFT) & DPU_DATA_CUBE_CHANNEL_CHANNEL__MASK)

#define DPU_BS_CFG_BS_ALU_ALGO(x) (((uint32_t)(x) << DPU_BS_CFG_BS_ALU_ALGO__SHIFT) & DPU_BS_CFG_BS_ALU_ALGO__MASK)
#define DPU_BS_CFG_BS_ALU_SRC(x) (((uint32_t)(x) << DPU_BS_CFG_BS_ALU_SRC__SHIFT) & DPU_BS_CFG_BS_ALU_SRC__MASK)
#define DPU_BS_CFG_BS_RELU_BYPASS(x) (((uint32_t)(x) << DPU_BS_CFG_BS_RELU_BYPASS__SHIFT) & DPU_BS_CFG_BS_RELU_BYPASS__MASK)
#define DPU_BS_CFG_BS_MUL_BYPASS(x) (((uint32_t)(x) << DPU_BS_CFG_BS_MUL_BYPASS__SHIFT) & DPU_BS_CFG_BS_MUL_BYPASS__MASK)

#define DPU_BS_OW_CFG_SIZE_E_2(x) (((uint32_t)(x) << DPU_BS_OW_CFG_SIZE_E_2__SHIFT) & DPU_BS_OW_CFG_SIZE_E_2__MASK)
#define DPU_BS_OW_CFG_SIZE_E_1(x) (((uint32_t)(x) << DPU_BS_OW_CFG_SIZE_E_1__SHIFT) & DPU_BS_OW_CFG_SIZE_E_1__MASK)
#define DPU_BS_OW_CFG_SIZE_E_0(x) (((uint32_t)(x) << DPU_BS_OW_CFG_SIZE_E_0__SHIFT) & DPU_BS_OW_CFG_SIZE_E_0__MASK)

#define DPU_WDMA_SIZE_0_CHANNEL_WDMA(x) (((uint32_t)(x) << DPU_WDMA_SIZE_0_CHANNEL_WDMA__SHIFT) & DPU_WDMA_SIZE_0_CHANNEL_WDMA__MASK)

#define DPU_WDMA_SIZE_1_HEIGHT_WDMA(x) (((uint32_t)(x) << DPU_WDMA_SIZE_1_HEIGHT_WDMA__SHIFT) & DPU_WDMA_SIZE_1_HEIGHT_WDMA__MASK)
#define DPU_WDMA_SIZE_1_WIDTH_WDMA(x) (((uint32_t)(x) << DPU_WDMA_SIZE_1_WIDTH_WDMA__SHIFT) & DPU_WDMA_SIZE_1_WIDTH_WDMA__MASK)

#define DPU_BN_CFG_BN_BYPASS(x) (((uint32_t)(x) << DPU_BN_CFG_BN_BYPASS__SHIFT) & DPU_BN_CFG_BN_BYPASS__MASK)

#define DPU_EW_CFG_EW_ALU_ALGO(x) (((uint32_t)(x) << DPU_EW_CFG_EW_ALU_ALGO__SHIFT) & DPU_EW_CFG_EW_ALU_ALGO__MASK)
#define DPU_EW_CFG_EW_ALU_SRC(x) (((uint32_t)(x) << DPU_EW_CFG_EW_ALU_SRC__SHIFT) & DPU_EW_CFG_EW_ALU_SRC__MASK)
#define DPU_EW_CFG_EW_RELU_BYPASS(x) (((uint32_t)(x) << DPU_EW_CFG_EW_RELU_BYPASS__SHIFT) & DPU_EW_CFG_EW_RELU_BYPASS__MASK)
#define DPU_EW_CFG_EW_MUL_BYPASS(x) (((uint32_t)(x) << DPU_EW_CFG_EW_MUL_BYPASS__SHIFT) & DPU_EW_CFG_EW_MUL_BYPASS__MASK)
#define DPU_EW_CFG_EW_BYPASS(x) (((uint32_t)(x) << DPU_EW_CFG_EW_BYPASS__SHIFT) & DPU_EW_CFG_EW_BYPASS__MASK)

#define DPU_OUT_CVT_CFG_OUT_CVT_BYPASS(x) (((uint32_t)(x) << DPU_OUT_CVT_CFG_OUT_CVT_BYPASS__SHIFT) & DPU_OUT_CVT_CFG_OUT_CVT_BYPASS__MASK)

#define DPU_LUT_CFG_LUT_LE_FUNCTION(x) (((uint32_t)(x) << DPU_LUT_CFG_LUT_LE_FUNCTION__SHIFT) & DPU_LUT_CFG_LUT_LE_FUNCTION__MASK)
#define DPU_LUT_CFG_LUT_UFLOW_PRIORITY(x) (((uint32_t)(x) << DPU_LUT_CFG_LUT_UFLOW_PRIORITY__SHIFT) & DPU_LUT_CFG_LUT_UFLOW_PRIORITY__MASK)

#define DPU_RDMA_RDMA_CFG_RDMA_DISABLE(x) (((uint32_t)(x) << DPU_RDMA_RDMA_CFG_RDMA_DISABLE__SHIFT) & DPU_RDMA_RDMA_CFG_RDMA_DISABLE__MASK)
#define DPU_RDMA_RDMA_CFG_RDMA_DATA_MODE(x) (((uint32_t)(x) << DPU_RDMA_RDMA_CFG_RDMA_DATA_MODE__SHIFT) & DPU_RDMA_RDMA_CFG_RDMA_DATA_MODE__MASK)
#define DPU_RDMA_RDMA_CFG_RDMA_DATA_SIZE(x) (((uint32_t)(x) << DPU_RDMA_RDMA_CFG_RDMA_DATA_SIZE__SHIFT) & DPU_RDMA_RDMA_CFG_RDMA_DATA_SIZE__MASK)
#define DPU_RDMA_RDMA_CFG_RDMA_DATA_USE(x) (((uint32_t)(x) << DPU_RDMA_RDMA_CFG_RDMA_DATA_USE__SHIFT) & DPU_RDMA_RDMA_CFG_RDMA_DATA_USE__MASK)

#define DPU_RDMA_RDMA_WEIGHT_E_WEIGHT(x) (((uint32_t)(x) << DPU_RDMA_RDMA_WEIGHT_E_WEIGHT__SHIFT) & DPU_RDMA_RDMA_WEIGHT_E_WEIGHT__MASK)
#define DPU_RDMA_RDMA_WEIGHT_N_WEIGHT(x) (((uint32_t)(x) << DPU_RDMA_RDMA_WEIGHT_N_WEIGHT__SHIFT) & DPU_RDMA_RDMA_WEIGHT_N_WEIGHT__MASK)
#define DPU_RDMA_RDMA_WEIGHT_B_WEIGHT(x) (((uint32_t)(x) << DPU_RDMA_RDMA_WEIGHT_B_WEIGHT__SHIFT) & DPU_RDMA_RDMA_WEIGHT_B_WEIGHT__MASK)
#define DPU_RDMA_RDMA_WEIGHT_M_WEIGHT(x) (((uint32_t)(x) << DPU_RDMA_RDMA_WEIGHT_M_WEIGHT__SHIFT) & DPU_RDMA_RDMA_WEIGHT_M_WEIGHT__MASK)

#endif /* MESA_HELPERS_H */

